/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package navigation;

/**
 *
 * @author kiry
 */
public class Navigation extends javax.swing.JFrame {

    /**
     * Creates new form Navigation
     */
    public Navigation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_history = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_playlist = new javax.swing.JLabel();
        lb_setting = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_home.setBackground(new java.awt.Color(255, 255, 255));
        lb_home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_home.setForeground(new java.awt.Color(255, 255, 255));
        lb_home.setText("Home");
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_homeMouseClicked(evt);
            }
        });
        jPanel1.add(lb_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/home1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/history1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        lb_history.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_history.setForeground(new java.awt.Color(255, 255, 255));
        lb_history.setText("History");
        lb_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_historyMouseClicked(evt);
            }
        });
        jPanel1.add(lb_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/playlist1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 20, 30));

        lb_playlist.setBackground(new java.awt.Color(255, 255, 255));
        lb_playlist.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_playlist.setForeground(new java.awt.Color(255, 255, 255));
        lb_playlist.setText("Playlist");
        lb_playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_playlistMouseClicked(evt);
            }
        });
        jPanel1.add(lb_playlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, 30));

        lb_setting.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_setting.setForeground(new java.awt.Color(255, 255, 255));
        lb_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/setting1.png"))); // NOI18N
        lb_setting.setText("Setting");
        lb_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_settingMouseClicked(evt);
            }
        });
        jPanel1.add(lb_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 910, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 1010));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, -1, 60));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(">");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, 30, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/bell2.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/qq.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, 20, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/profileBorder.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 0, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/whiteSquare.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 0, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1630, 50));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_homeMouseClicked

    private void lb_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_historyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_historyMouseClicked

    private void lb_playlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_playlistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_playlistMouseClicked

    private void lb_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_settingMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lb_settingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_history;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_playlist;
    private javax.swing.JLabel lb_setting;
    // End of variables declaration//GEN-END:variables
}
